name: tisa
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.23
  - scipy>=1.10
  - pandas>=1.5
  - numba>=0.57
  - matplotlib>=3.7
  - yfinance>=0.2
  - pyyaml>=6
  - tqdm>=4.64
  - dtaidistance>=2.3.12
  - tslearn>=0.6.2
  - scikit-learn>=1.1
  - hypothesis>=6.82
  - pip
  - pip:
      - fastdtw
